In [1]:
import pandas as pd

# Task 1
У вас є дані про користувачів із полями: "Ім'я", "Вік" і "Місто".
* Створіть DataFrame зі словника Python із п'ятьма записами.
* Виведіть весь DataFrame.
* Визначте кількість рядків і стовпців.
* Виведіть назви всіх стовпців.
* Покажіть перші три рядки таблиці.

In [2]:
dict_users = {
    "Name": ["Oleg", "Nikita", "Alexandr", "Alexey"],
    "Age": [22, 35, 44, 12],
    "City": ["Kiev", "Odesa", "Xarkiv", "Mukolaiv"]
}

users = pd.DataFrame(dict_users)

In [3]:
print("total count rows: %d and columns: %d" % (
    len(users.index),
    len(users.columns)
))

total count rows: 4 and columns: 3

In [4]:
users.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
print("All column names:", ", ".join(users.columns))

All column names: Name, Age, City

In [6]:
users.head(3)

       Name  Age    City
0      Oleg   22    Kiev
1    Nikita   35   Odesa
2  Alexandr   44  Xarkiv

# Task 2
У файлі CSV збережено дані про фільми: "Назва", "Жанр", "Рік", "Рейтинг".
* Прочитайте дані з CSV у DataFrame.
* Виведіть перші п'ять рядків таблиці.
* Визначте загальну кількість рядків і стовпців.
* Визначте типи даних для кожного стовпця.
* Перевірте наявність пропусків.

In [7]:
data = {'Name': ['Anna', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['Odesa', 'London', 'New York']
       }
df = pd.DataFrame(data)

In [8]:
df.to_csv('output.csv', index=False, encoding='utf-8')

In [9]:
movies = pd.read_csv("./notes02_2.csv")

movies.head()

                                          Назва        Жанр     Рік  Рейтинг
0                       F1:Фільм (F1:The Movie)       Спорт  2025.0      7.8
1                    Субстанція (The Substance)        Жахи  2024.0      7.8
2                     Оппенгеймер (Oppenheimer)   Біографія  2023.0      8.4
3  Аватар: Шлях води (Avatar: The Way of Water)  Фантастика  2022.0      7.6
4                                   Дюна (Dune)  Фантастика  2021.0      8.0

In [10]:
print("total rows: %d and columns: %d" % (
    len(movies.index),
    len(movies.columns)
))

total rows: 10 and columns: 4

In [11]:
print("Data types for every column: ", movies.dtypes, sep="\n")

Data types for every column:
Назва          str
Жанр           str
Рік        float64
Рейтинг    float64
dtype: object

In [12]:
import numpy as np

In [13]:
empties = movies.isnull()
print(empties)
positions = np.where(empties)
print(positions, len(positions))
print(*zip(*positions))

   Назва   Жанр    Рік  Рейтинг
0  False  False  False    False
1  False  False  False    False
2  False  False  False    False
3  False  False  False    False
4  False  False  False    False
5  False  False  False    False
6  False   True  False    False
7  False  False  False    False
8  False  False  False    False
9  False  False   True    False
(array([6, 9]), array([1, 2])) 2
(np.int64(6), np.int64(1)) (np.int64(9), np.int64(2))

In [14]:
print("gaps are found by indexes: ",
      ", ".join(f"({x};{y})" for (x,y) in zip(*positions))
)

gaps are found by indexes:  (6;1), (9;2)

# Task 3
Є таблиця співробітників із колонками: "Ім'я", "Вік", "Відділ", "Зарплата".
* Створіть DataFrame з не менш ніж п'ятьма рядками.
* Виведіть усі рядки, де зарплата вища за 50000.
* Відсортуйте таблицю за віком у порядку зростання.
* Відсортуйте таблицю за зарплатою в порядку спадання.

In [15]:
workers = pd.DataFrame({
        'Name': ['Anna', 'Bob', 'Charlie', 'New York', 'New York'],
        'Age': [25, 30, 39, 41, 25],
        'Department': ['Odesa', 'London', 'New York', 'New York', 'New York'],
        'Salary': [20000, 40000, 60000, 80000, 100000],  
       })
workers[workers['Salary'] > 50000]

       Name  Age Department  Salary
2   Charlie   39   New York   60000
3  New York   41   New York   80000
4  New York   25   New York  100000

In [16]:
workers.sort_values(by='Age', ascending=True)

       Name  Age Department  Salary
0      Anna   25      Odesa   20000
4  New York   25   New York  100000
1       Bob   30     London   40000
2   Charlie   39   New York   60000
3  New York   41   New York   80000

In [17]:
workers.sort_values(by='Salary', ascending=False)

       Name  Age Department  Salary
4  New York   25   New York  100000
3  New York   41   New York   80000
2   Charlie   39   New York   60000
1       Bob   30     London   40000
0      Anna   25      Odesa   20000

# Task 4
Доступні дані про продажі з колонками: "Товар", "Категорія", "Ціна", "Кількість".
* Створіть DataFrame з не менш ніж десятьма рядками.
* Виведіть вихідний DataFrame.
* Додайте новий стовпець "Виручка" як добуток ціни та кількості.
* Виведіть оновлений DataFrame.

In [18]:
products = pd.read_csv("./products02_2.csv")
products[['Товар', 'Категорія', 'Ціна', 'Кількість', ]].head(3)

              Товар    Категорія   Ціна  Кількість
0       Ноутбук Pro  Електроніка  45000          5
1  Мишка бездротова    Аксесуари   1200         50
2    Клавіатура RGB    Аксесуари   2500         20

In [19]:
# products['Multiply'] = products['Ціна'] * products['Кількість']
products.head(3)

   ID             Товар    Категорія   Ціна  Кількість
0   1       Ноутбук Pro  Електроніка  45000          5
1   2  Мишка бездротова    Аксесуари   1200         50
2   3    Клавіатура RGB    Аксесуари   2500         20

# Task 5
Є список студентів із зазначенням: "Ім'я", "Курс", "Оцінка".
* Створіть DataFrame і заповніть його не менш ніж вісьмома рядками.
* Виведіть вихідний DataFrame.
* Обчисліть середню оцінку за кожним курсом.
* Знайдіть максимальну та мінімальну оцінку за кожним курсом.

In [20]:
students = pd.read_csv('./students02_2.csv')
students.head(3)

               Ім'я                  Курс  Оцінка
0  Олександр Коваль   Математичний аналіз      12
1      Марія Бондар  Дискретна математика      10
2   Андрій Ткаченко  Програмування Python      11

In [21]:
marks = students.groupby('Курс')['Оцінка']
print('Middle mark at course:', marks.mean(), sep='\n')

Middle mark at course:
Курс
Алгоритми та структури     9.000000
Бази даних                 9.000000
Дискретна математика       9.333333
Математичний аналіз        9.666667
Програмування Python      11.666667
Name: Оцінка, dtype: float64

In [22]:
mean_marks = marks.mean()
print(f"Min: {mean_marks.idxmin()} ({mean_marks.min()}), Max: {mean_marks.idxmax()} ({mean_marks.max()})")

Min: Алгоритми та структури (9.0), Max: Програмування Python (11.666666666666666)

# Task 6
Зібрано дані про товари та продажі у двох таблицях. Перша містить: "ID", "Назва", "Ціна". Друга містить: "ID", "Кількість".
* Створіть два DataFrame і заповніть їх не менш ніж п'ятьма рядками.
* Виведіть обидва DataFrame.
* Об'єднайте їх за колонкою "ID".
* Додайте новий стовпець "Сума" як добуток ціни та кількості.
* Виведіть підсумковий DataFrame.

In [23]:
sales = pd.read_csv('./sales02_2.csv')
print(products.head(3))
print(sales.head(3))

   ID             Товар    Категорія   Ціна  Кількість
0   1       Ноутбук Pro  Електроніка  45000          5
1   2  Мишка бездротова    Аксесуари   1200         50
2   3    Клавіатура RGB    Аксесуари   2500         20
   ID  Продано
0   1        3
1   2        7
2   3        9

In [24]:
results = pd.merge(products, sales, on='ID', how='inner')
results.head()

   ID             Товар    Категорія   Ціна  Кількість  Продано
0   1       Ноутбук Pro  Електроніка  45000          5        3
1   2  Мишка бездротова    Аксесуари   1200         50        7
2   3    Клавіатура RGB    Аксесуари   2500         20        9
3   4       Монітор 27"    Периферія  12000         10        8
4   5        Смартфон X      Гаджети  28000         15        4

In [29]:
results['Сума'] = results['Ціна'] * results['Продано']
results.head()

   ID             Товар    Категорія   Ціна  Кількість  Продано    Сума
0   1       Ноутбук Pro  Електроніка  45000          5        3  135000
1   2  Мишка бездротова    Аксесуари   1200         50        7    8400
2   3    Клавіатура RGB    Аксесуари   2500         20        9   22500
3   4       Монітор 27"    Периферія  12000         10        8   96000
4   5        Смартфон X      Гаджети  28000         15        4  112000